version: '3.9'

services:

  workspace:
    image: workspace:latest
    #build: .
    ports: 
      - 7733:7733
    environment: 
      DEBUG: "true"
      SCRAPP_BROWSER_WS_ENDPOINT: http://37.59.47.214:3040/?token=MY-SUPER-SECRET-TOKEN
    # volumes: 
    #   - ./:/app
    command: ["yarn", "dev"]

networks:
  default:
    name: scrapp-net
    external: true