version: '3.9'

services:

  workspace:
    image: workspace:latest
    ports: 
      - 7733:7733
    environment: 
      DEBUG: ${DEBUG}
      SCRAPP_BROWSER_WS_ENDPOINT: ${SCRAPP_BROWSER_WS_ENDPOINT}
    volumes: 
      - /root/.coder-config/workspace:/app
    command: ["yarn", "dev"]

networks:
  default:
    name: scrapp-net
    external: true